# Site settings
title: Physics Society 
description: "IIT Kanpur Physics Society"  # used in site head

# footer details. Deleting the value would remove it from footer.
facebook_username: PhysicsSocietyIITk
email: karmakar@iitk.ac.in
copyright_name: Physics Society
rss : true

# used for portfolio on home page
collections:
  - projects

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888

# gem dependencies
plugins: [jekyll-feed]
