# Site settings
title: Physics Society UG Wing
description: "IIT Kanpur Physics Society"  # used in site head

# footer details. Deleting the value would remove it from footer.
facebook_username: PhysicsSocietyIITk
email: physics.society.ug@gmail.com
rss : true

# used for portfolio on home page
collections:
  - projects
  - people

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888

# gem dependencies
plugins: [jekyll-feed]
